### PR TITLE
fix: slugify item name for content disposition

### LINKED ISSUE #32: bug: name of exported zip files can be arbitrary
When exporting zips, the server sets the `Content-Disposition` header to a user-controlled value:

https://github.com/graasp/graasp-plugin-item-zip/blob/e551ca0e52b3f33437a088afceb7298bf07b6ee0/src/utils/utils.ts#L378

This has multiple severe implications:
- item names can crash the server, as they may contain characters that are illegal in HTTP headers
- this can be done *intentionally*, as the value is entirely user-controlled
- it allows arbitrary HTTP header / content injection, as no sanitization is performed before writing the item name into the header. So for instance an item name string such as `foo.zip" <arbitrary fields>` allows modification of the content-disposition header.

### PR DESCRIPTION
**Pull request by pyphilia**
I didn't see you assigned yourself, but since there's no PR I've done it @dialexo  ^^
I've used slugify https://www.npmjs.com/package/slugify to handle the item name, it looks good for accents and weird characters.

close #32

### CODE REVIEW

File: src/utils/utils.ts [hunk 1]
```diff
@@ -375,7 +376,7 @@ export const prepareArchiveFromItem = async ({
     zipStream.on('close', () => {
       // set reply headers depending zip file and return file
       const buffer = fs.readFileSync(zipPath);
-      reply.raw.setHeader('Content-Disposition', `filename="${item.name}.zip"`);
+      reply.raw.setHeader('Content-Disposition', `filename="${slugify(item.name)}.zip"`);
```
Comment (dialexo) [inline src/utils/utils.ts:379]:
```suggestion
      reply.raw.setHeader('Content-Disposition', `filename="${slugify(item.name, { remove: /["'`]/g })}.zip"`);
```

**Review by dialexo — CHANGES_REQUESTED** [review]
Thank you! That's exactly what I intended to do, but after some testing I don't think it is enough. Indeed consider the following case:
```node
> slugify('"test')
'"test'
```
So header injection is still possible. I think we can pass a `remove` options with a global regex to remove quotes, but I don't know if that is enough. From the docs, default options don't do much:

```ts
slugify('some string', {
  replacement: '-',  // replace spaces with replacement character, defaults to `-`
  remove: undefined, // remove characters that match regex, defaults to `undefined`
  lower: false,      // convert to lower case, defaults to `false`
  strict: false,     // strip special characters except replacement, defaults to `false`
  locale: 'vi',       // language code of the locale to use
  trim: true         // trim leading and trailing replacement chars, defaults to `true`
})
```

File: src/utils/utils.ts (hunk 1 above)
Comment (pyphilia) [reply src/utils/utils.ts:379]: I'll apply your suggested change and merge, it's still better than nothing as we had. I've opened an issue for when we have time to investigate longer.
